### ISSUE TITLE
Crash on ::findjsobjects -r with Node v4.3.1 (V8 4.5.103.35)

### ISSUE THREAD

**Issue by andrija-hers** [joyent/mdb_v8#68] opened 2016-06-02 15:52 UTC
Hi, not glad to report that the master branch's
`::findjsobjects -r`
crashes on NodeJS Image 15.4.1 (NodeJS version 4.3.1):

```
[root@nodejs-15_4_1 ~]# mdb -p 94743
Loading modules: [ ld.so.1 libumem.so.1 libc.so.1 ]
> ::load /root/mdb_v8.so
mdb_v8 version: 1.1.2 (dev)
V8 version: 4.5.103.35
Autoconfigured V8 support from target
C++ symbol demangling enabled
> 521609209::findjsobjects -r

*** mdb: received signal SEGV at:
    [1] mdb_v8.so`findjsobjects_references_add+0x0()
    [2] mdb_v8.so`jsobj_properties+0xea()
    [3] mdb_v8.so`dcmd_findjsobjects+0x4f0()
    [4] mdb`dcmd_invoke+0x7c()
    [5] mdb`mdb_call_idcmd+0x112()
    [6] mdb`mdb_call+0x3e1()
    [7] mdb`yyparse+0xd7c()
    [8] mdb`mdb_run+0x2cd()
    [9] mdb`main+0xc9d()
    [10] mdb`_start+0x6c()

mdb: (c)ore dump, (q)uit, (r)ecover, or (s)top for debugger [cqrs]? 
```

**Comment by rmustacc** [comment] 2016-06-02 16:06
On 6/2/16 8:52 , Andrija Petrovic wrote:
> mdb: (c)ore dump, (q)uit, (r)ecover, or (s)top for debugger [cqrs]? 
> ```

Could you select the core dump option and make the core available please?

**Comment by misterdjules** [comment] 2016-06-02 16:15
@rmustacc The crash can be reproduced by generating a core file with node v4.3.1 (not sure yet if it's specific to that version or a range of versions) and running `::findjsobjects -r` on any object.

**Comment by misterdjules** [comment] 2016-06-02 16:24
After bisecting, breaking change seems to be 105b061b055b5d8ad714a7fab9ab14c6c257f94b.

**Comment by misterdjules** [comment] 2016-06-02 17:20
I should have a PR that fixes this crash shortly. I'm currently putting together a regression test.

**Comment by misterdjules** [comment] 2016-06-02 18:54
PR submitted. at #69.

**Comment by misterdjules** [comment] 2016-06-02 23:28
Fixed by https://github.com/joyent/mdb_v8/commit/259e534aa8d3217a0e2f5ef2c8070f148b4d805c.

**Closed by misterdjules** 2016-06-02 23:28 UTC

**Comment by andrija-hers** [comment] 2016-06-03 08:16
Wonderful! Now, it would be great if this state of mdb_v8 makes its way to the official 15.4.1 Joyent NodeJs image...

**Comment by misterdjules** [comment] 2016-06-08 17:06
@andrija-hers

mdb_v8 comes from the platform, not from container images. We could update mdb_v8 in the platform, but currently, the recommended way for updating mdb_v8 is to [download the latest release using the instructions in the README file](https://github.com/joyent/mdb_v8#binary-downloads), and explicitly load that downloaded file using `::load /path/to/file`.

This process can be made simpler by storing the latest `mdb_v8_{amd64,ia32}.so` files into a separate directory, say `~/mdb_dmods`, and use `mdb -L ~/mdb_dmods` to start mdb. Then `::load v8` should load the v8 dmod from `~/mdb_dmods`.

Let me know if that's a reasonable solution for your needs.

**Comment by andrija-hers** [comment] 2016-06-09 07:38
@misterdjules 
many thanks for the info! We're currently updating the platform with the latest release.
Meanwhile, we're explicitly loading using the `::load /path/to/file`, which is a completely suitable option.
