### ISSUE TITLE
Node v6.6.0 issues

### ISSUE THREAD

**Issue by geek** [joyent/mdb_v8#77] opened 2016-09-19 18:42 UTC
```
db_v8 version: 1.1.3 (release, from 9d5bc8b)
V8 version: 5.1.281.83
mdb: failed to read "v8dbg_off_fp_marker": unknown symbol name
mdb: couldn't find class "SharedFunctionInfo", field "inferred_name"
mdb: failed to autoconfigure from target; commands may have incorrect results!
```

^^^ The result of using mdb with a core dump from node v6.6.0 on SmartOS.

**Comment by michaelnisi** [comment] 2017-01-19 19:48
Is this moving in any direction?

**Comment by misterdjules** [comment] 2017-01-19 22:20
@michaelnisi I've investigated these failures and found the root cause(s), it shouldn't be long to fix them. I just haven't found the time to do that yet and we currently don't have a use case for it . However, since you expressed interest in getting that fixed, I'll move that up in my todo list and try to get that done sooner rather than later.

**Comment by michaelnisi** [comment] 2017-01-20 07:40
@misterdjules Hey thanks! Doesn’t the latest SmartOS image come with nodejs-7.2.1? Why wouldn’t I expect mdb to work with the installed Node version? Could you provide some insight?

**Comment by misterdjules** [comment] 2017-01-20 19:52
@michaelnisi mdb_v8 is not bundled with node and is not part of the SmartOS images, so there's not a formal contract that guarantees that any mdb_v8 version works with the latest node version shipped in the latest pkgsrc repositories.

Usually, mdb_v8 is updated as new node versions are released, so in the past mdb_v8 has supported latest node versions, but recently a few node versions fell through the cracks.

When that happens, you can file an issue here and we should be able to help fairly quickly.

**Comment by misterdjules** [comment] 2017-01-25 02:02
I made some good progress on this. There's [a branch in my fork named fix-issue-77](https://github.com/misterdjules/mdb_v8/tree/fix-issue-77) that solves the problems documented in this issue for all node 6.x versions.

You should now be able to work with core files generated with node versions >= 6.6.0 by using a mdb_v8.so dmod built from that branch.

Before submitting a PR with these changes, there's still a few questions remaining about what should be considered an anonymous function with these versions of node. However, it shouldn't impact much of the everyday usage of mdb_v8, or at least it shouldn't be a concern for users who need to be able to simply use mdb_v8 with node versions >= 6.6.0 now or in the short term.

**Comment by misterdjules** [comment] 2017-01-25 23:42
I just realized that we had previously filed #75 for the following problem in this issue:

```
mdb: couldn't find class "SharedFunctionInfo", field "inferred_name"
```.

Because this issue (#77) is what I used to do the work to fix #75, I'll mark #75 as a duplicate.

**Comment by misterdjules** [comment] 2017-01-25 23:50
PR at https://cr.joyent.us/1340.

**Comment by misterdjules** [comment] 2017-01-26 00:46
PR to add post-mortem metadata generation for `CommonFrameConstants::kContextOrFrameTypeOffset` to V8 can be found at https://codereview.chromium.org/2655553006.

**Comment by michaelnisi** [comment] 2017-01-27 09:19
Thank you, @misterdjules. With your [branch](https://github.com/misterdjules/mdb_v8/tree/fix-issue-77) and Node v6.9.2 (V8 5.1.281.88) I’ve got:

```
> ::load mdb_v8/build/amd64/mdb_v8.so
mdb_v8 version: 1.1.4 (dev)
mdb: failed to determine V8 version: unknown symbol name
```

This is with **mdb** version:

```
> ::showrev
Hostname: maybe
Release: 5.11
Kernel architecture: i86pc
Application architecture: amd64
Kernel version: SunOS 5.11 i86pc joyent_20170119T014200Z
Platform: i86pc
>
```

**Comment by michaelnisi** [comment] 2017-01-27 11:39
Oh, but that seems to be no problem, I’ve just realized, I can just carry on:

```
> ::load mdb_v8/build/amd64/mdb_v8.so
mdb_v8 version: 1.1.4 (dev)
mdb: failed to determine V8 version: unknown symbol name
> ::load mdb_v8/build/amd64/mdb_v8.so
mdb: mdb_v8 module is already loaded
```

I gotta run, looking forward to inspect some actual core dumps later.

**Comment by michaelnisi** [comment] 2017-01-27 17:44
Sorry, my fault—zone wasn’t configured to dump core files, after:

```
coreadm -g /var/cores/%f.%n.%p.%t.core -e global -e global-setid -e log -d process -d proc-setid
```

It’s fine:

```
> ::load mdb_v8/build/amd64/mdb_v8.so
mdb_v8 version: 1.1.4 (dev)
V8 version: 5.1.281.88
Autoconfigured V8 support from target
C++ symbol demangling enabled
```

**Comment by michaelnisi** [comment] 2017-01-27 17:58
Or, to be complete, I ran **mdb** without core file.

**Comment by misterdjules** [comment] 2017-01-27 18:01
@michaelnisi Excellent, thank you for the feedback! Let us know if there's anything else we can do to help.

**Comment by misterdjules** [comment] 2017-01-27 18:02
Fixed by https://github.com/joyent/mdb_v8/commit/d88c5714cfffed874e77e1186d0f0fffb92f7d09. Will try to get that in a new release soon.

**Closed by misterdjules** 2017-01-27 18:02 UTC
